# Site settings
title: Jean-François Bustarret
email: jf [] bustarret [] com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts, useful tools & ressources.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jf.bustarret.com" # the base hostname & protocol for your site
twitter_username: jfbus
github_username:  jfbus

# Build settings
markdown: kramdown
